### ISSUE TITLE
Specify build folder as argument

### ISSUE THREAD

**Issue by darraghmckay** [jnsjknn/compress-create-react-app#1]
I'm using a multi-package setup with lerna and yarn workspaces 

As such, my `build` dir is actually `packages/apps/projectname/build` 

It would be great if you could specify that as a CLI argument

I might take a go at it

**Comment by jnsjknn** [comment]
I agree that it should be a function in this package. I think it could also be nice to also allow using a config file to specify the build location. 

If you're able to work on the changes, feel free to fork the repo and make a pull request.

**Comment by jnsjknn** [comment]
@darraghmckay Are you working on this?

**Comment by darraghmckay** [comment]
Sorry @jnsjknn I'm not, I ended up using a different library. Feel free to close this it you want

**Comment by jnsjknn** [comment]
@darraghmckay

No worries. I was just checking to make sure we won't work on the same thing in parallel.

**Comment by jnsjknn** [comment]
@darraghmckay This is now a feature of this package (from version 1.1.0 onwards).
