### ISSUE TITLE
EOF running out of memory

### ISSUE THREAD

**Issue by billnbell** [jnsjknn/compress-create-react-app#13]
How much memory does compress-cra need?

Can we limit it?

If this is a fork() do we need to increase NODE parameters for forking?

**Comment by jnsjknn** [comment]
Hi @billnbell, there's not really much I can do based on this information. Would you be able to provide more information so that I might be able to reproduce the error?

Are you working on a project with a lot of files or very large files? How much RAM does your system have?

**Comment by billnbell** [comment]
It is only < 20 files. Really small. We had it set to 4092 MB and it was getting EOF error. We were able to increase the mem to 6144 MB and it started working again. It seems like a lot of memory for just compressing. Considering Bitbucket pipelines only allows 8MB max.

**Comment by jnsjknn** [comment]
This should be resolved in the next version using a new option in the config file.
