### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by brampurnot** [jnsjknn/compress-create-react-app#14]
Hi there!

We just upgraded to the latest version (1.4.1) and we are having an issue when using the compress-cra command when building the app on a Mac. It seems that we have the same issue on Linux. 

env: node\r: No such file or directory

Issue is caused by carriage return on Windows vs. mac. Have you seen this issue before? 

Bram

**Comment by jnsjknn** [comment]
Hi, I will try to reproduce this issue on a Linux machine and do my best fix it. I'm just currently very busy with my day job, so it could take a while. 

Did you previously use a different version which worked fine? If so, you should revert back to the previous version until I have time to resolve this issue.

If you have time and know how to fix the issue, feel free to create a pull request.

**Comment by jnsjknn** [comment]
It turned out a single file was using CRLF instead of LF. I fixed it and added a check for line endings in the precommit hook. Version 1.4.2 should work as expected.
