### ISSUE TITLE
Add to my framework

### ISSUE THREAD

**Issue by MurageKibicho** [jnsjknn/compress-create-react-app#15]
Good morning, 
I hope this message finds you well. I found impressive your library and I hope to implement some functions in the [create-new-startup](https://github.com/kibichomurage/create-new-startup) bundler. 

I was writing to formally seek your permission before I implemented a portion of your codebase. I'm only taking functions that interest me. Is there an attribution style you prefer? Thank you.

**Comment by jnsjknn** [comment]
Hi, the code is [licensed](https://github.com/jnsjknn/compress-create-react-app/blob/master/LICENCE.md) under the MIT license. Feel free to use it as is
