### ISSUE TITLE
How to server this compressed files

### ISSUE THREAD

**Issue by VenomFate-619** [jnsjknn/compress-create-react-app#9]
How to sever index.html.br and all static files like main.t534534.js.br and main.css.css.br
![image](https://user-images.githubusercontent.com/67755128/159395942-bbaeae1c-a321-47ae-88df-4af77fa7febc.png)

**Comment by jnsjknn** [comment]
What tech are you using for your server? Is it an express.js server?

**Comment by VenomFate-619** [comment]
It is a react app hosted on netify
If required I can use express server

**Comment by jnsjknn** [comment]
I'm not familiar with netify but it shouldn't be very complicated to make a server serve file.ext.br instead of file.ext. See of netify's documentation helps you.

I'm closing this since it is not an issue with compress-CRA.

**Comment by MurageKibicho** [comment]
I had the same question. How do I serve Brotli files in production. I know I need a Brotli decoder but I can't wrap my head around the implementation. Do you have any tutorials showing how to deploy on a service like Heroku, Vercel or whatever you use? Thank you.

**Comment by jnsjknn** [comment]
@MurageKibicho You should be able to serve the brotli files directly. The exact way to do it depends on your server. Are you using Express.js?
